/*
 * Xplainit C/C++ FFI Bindings
 * 
 * Natural language explanations for C/C++ code execution.
 * 
 * This is an automatically generated header file.
 * Do not modify manually.
 */


#ifndef XPLAINIT_H
#define XPLAINIT_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque handle to a runtime instance
 */
typedef struct XplainitHandle XplainitHandle;

/*
 Create a new Xplainit runtime instance

 # Returns
 Pointer to XplainitHandle on success, null on failure

 # Safety
 The returned pointer must be freed with xplainit_free()
 */
struct XplainitHandle *xplainit_create(void);

/*
 Free a Xplainit runtime instance

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 and must not be used after this call
 */
void xplainit_free(struct XplainitHandle *handle);

/*
 Enable tracing for a runtime instance

 # Arguments
 * `handle` - Valid XplainitHandle pointer

 # Returns
 1 on success, 0 on failure

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 */
int32_t xplainit_enable(struct XplainitHandle *handle);

/*
 Disable tracing for a runtime instance

 # Arguments
 * `handle` - Valid XplainitHandle pointer

 # Returns
 1 on success, 0 on failure

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 */
int32_t xplainit_disable(struct XplainitHandle *handle);

/*
 Check if tracing is enabled

 # Arguments
 * `handle` - Valid XplainitHandle pointer

 # Returns
 1 if enabled, 0 if disabled or invalid handle

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 */
int32_t xplainit_is_enabled(struct XplainitHandle *handle);

/*
 Get captured events as JSON string

 # Arguments
 * `handle` - Valid XplainitHandle pointer

 # Returns
 Pointer to null-terminated JSON string on success, null on failure
 The returned string must be freed with xplainit_free_string()

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 */
char *xplainit_get_events(struct XplainitHandle *handle);

/*
 Clear all captured events

 # Arguments
 * `handle` - Valid XplainitHandle pointer

 # Returns
 1 on success, 0 on failure

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 */
int32_t xplainit_clear_events(struct XplainitHandle *handle);

/*
 Get statistics about captured events

 # Arguments
 * `handle` - Valid XplainitHandle pointer
 * `total_events` - Output pointer for total event count (can be null)
 * `function_calls` - Output pointer for function call count (can be null)
 * `errors` - Output pointer for error count (can be null)

 # Returns
 1 on success, 0 on failure

 # Safety
 The handle must be a valid pointer returned from xplainit_create()
 The output pointers, if not null, must be valid
 */
int32_t xplainit_get_statistics(struct XplainitHandle *handle,
                                uintptr_t *total_events,
                                uintptr_t *function_calls,
                                uintptr_t *errors);

/*
 Record a function entry event

 # Arguments
 * `handle` - Valid XplainitHandle pointer
 * `name` - Function name (null-terminated C string, may be null)
 * `file` - Source file (null-terminated C string, may be null)
 * `line` - Source line number

 # Returns
 1 if the event was recorded, 0 otherwise (null handle or tracing disabled)

 # Safety
 The handle must be a valid pointer returned from xplainit_create().
 `name` and `file`, if not null, must point to valid null-terminated C strings.
 */
int32_t xplainit_on_function_enter(struct XplainitHandle *handle,
                                   const char *name,
                                   const char *file,
                                   uint32_t line);

/*
 Record a function exit event

 # Arguments
 * `handle` - Valid XplainitHandle pointer
 * `name` - Function name (null-terminated C string, may be null)
 * `file` - Source file (null-terminated C string, may be null)
 * `line` - Source line number

 # Returns
 1 if the event was recorded, 0 otherwise (null handle or tracing disabled)

 # Safety
 The handle must be a valid pointer returned from xplainit_create().
 `name` and `file`, if not null, must point to valid null-terminated C strings.
 */
int32_t xplainit_on_function_exit(struct XplainitHandle *handle,
                                  const char *name,
                                  const char *file,
                                  uint32_t line);

/*
 Record an exception event

 # Arguments
 * `handle` - Valid XplainitHandle pointer
 * `error_type` - Exception type (null-terminated C string, may be null)
 * `message` - Exception message (null-terminated C string, may be null)
 * `file` - Source file (null-terminated C string, may be null)
 * `line` - Source line number

 # Returns
 1 if the event was recorded, 0 otherwise (null handle or tracing disabled)

 # Safety
 The handle must be a valid pointer returned from xplainit_create().
 The string arguments, if not null, must point to valid null-terminated C strings.
 */
int32_t xplainit_on_exception(struct XplainitHandle *handle,
                              const char *error_type,
                              const char *message,
                              const char *file,
                              uint32_t line);

/*
 Free a string returned by xplainit_get_events()

 # Safety
 The string must be a valid pointer returned from xplainit_get_events()
 and must not be used after this call
 */
void xplainit_free_string(char *s);

/*
 Get version string

 # Returns
 Pointer to static null-terminated version string

 # Safety
 This function is always safe to call
 */
const char *xplainit_version(void);

#endif  /* XPLAINIT_H */
